"""empty message

Revision ID: 09f8f0eafd00
Revises: 8db2da9efb4e
Create Date: 2020-09-04 21:16:27.894734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f8f0eafd00'
down_revision = '8db2da9efb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambience_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['business_client.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('centre_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['business_client.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipments_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['business_client.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['business_client.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_image')
    op.drop_table('equipments_image')
    op.drop_table('centre_image')
    op.drop_table('ambience_image')
    # ### end Alembic commands ###
