"""empty message

Revision ID: 1429bb3e8c80
Revises: 9edf5a86b6c0
Create Date: 2020-09-26 17:36:59.383958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1429bb3e8c80'
down_revision = '9edf5a86b6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['business_client.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('business_client', sa.Column('locality', sa.String(length=255), nullable=True))
    op.add_column('business_client', sa.Column('partnership', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_client', 'partnership')
    op.drop_column('business_client', 'locality')
    op.drop_table('service_image')
    # ### end Alembic commands ###
