"""empty message

Revision ID: 20b88f0c5dd6
Revises: 1429bb3e8c80
Create Date: 2020-09-28 20:18:29.821386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b88f0c5dd6'
down_revision = '1429bb3e8c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_client', sa.Column('business_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_client', 'business_type')
    # ### end Alembic commands ###
