"""empty message

Revision ID: 4dee6cc0b2ee
Revises: 259e204029a6
Create Date: 2020-10-15 21:59:16.804532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dee6cc0b2ee'
down_revision = '259e204029a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.add_column('booking', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking', 'payment', ['payment_id'], ['booking_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'payment_id')
    op.drop_table('payment')
    # ### end Alembic commands ###
