"""empty message

Revision ID: 52c1d9e13db4
Revises: 09f8f0eafd00
Create Date: 2020-09-05 14:04:51.288665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c1d9e13db4'
down_revision = '09f8f0eafd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_client', sa.Column('updated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_client', 'updated')
    # ### end Alembic commands ###
