"""empty message

Revision ID: 61f1fb471b69
Revises: 83f56c85de7f
Create Date: 2020-10-17 18:01:03.456642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f1fb471b69'
down_revision = '83f56c85de7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'service')
    # ### end Alembic commands ###
