"""empty message

Revision ID: 83f56c85de7f
Revises: 4dee6cc0b2ee
Create Date: 2020-10-17 14:09:20.379522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f56c85de7f'
down_revision = '4dee6cc0b2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_client', sa.Column('lat', sa.String(length=24), nullable=True))
    op.add_column('business_client', sa.Column('lng', sa.String(length=24), nullable=True))
    op.add_column('business_client', sa.Column('place_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_client', 'place_id')
    op.drop_column('business_client', 'lng')
    op.drop_column('business_client', 'lat')
    # ### end Alembic commands ###
