"""empty message

Revision ID: 8ad3b22d0a9a
Revises: f7c00a0c23df
Create Date: 2020-09-05 18:14:45.940503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad3b22d0a9a'
down_revision = 'f7c00a0c23df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_client', sa.Column('close_time', sa.Time(), nullable=True))
    op.add_column('business_client', sa.Column('day_from', sa.String(length=20), nullable=True))
    op.add_column('business_client', sa.Column('day_to', sa.String(length=20), nullable=True))
    op.add_column('business_client', sa.Column('open_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_client', 'open_time')
    op.drop_column('business_client', 'day_to')
    op.drop_column('business_client', 'day_from')
    op.drop_column('business_client', 'close_time')
    # ### end Alembic commands ###
