"""empty message

Revision ID: 8db2da9efb4e
Revises: 2de49ca529c9
Create Date: 2020-08-27 21:47:18.170718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db2da9efb4e'
down_revision = '2de49ca529c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'paid')
    # ### end Alembic commands ###
