"""empty message

Revision ID: 8f58201baee2
Revises: 20b88f0c5dd6
Create Date: 2020-10-03 13:20:29.621824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f58201baee2'
down_revision = '20b88f0c5dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_client', sa.Column('otp', sa.String(length=20), nullable=True))
    op.add_column('business_client', sa.Column('otp_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_client', 'otp_verified')
    op.drop_column('business_client', 'otp')
    # ### end Alembic commands ###
