"""empty message

Revision ID: 9b1595a4c40d
Revises: 8f58201baee2
Create Date: 2020-10-04 20:31:56.544688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1595a4c40d'
down_revision = '8f58201baee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_client.client_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('booking', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking', 'user', ['user_id'], ['user'])
    op.add_column('user', sa.Column('mobile_number', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mobile_number')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'user_id')
    op.drop_table('cart')
    # ### end Alembic commands ###
