"""empty message

Revision ID: a2cfba9ef320
Revises: a760ab285ac1
Create Date: 2020-11-11 10:57:35.708642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cfba9ef320'
down_revision = 'a760ab285ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_n_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=255), nullable=True),
    sa.Column('review', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['business_client.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating_n_review')
    # ### end Alembic commands ###
