"""empty message

Revision ID: c97bd949105a
Revises: 6f39f01dae19
Create Date: 2020-09-10 20:24:44.736568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c97bd949105a'
down_revision = '6f39f01dae19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_at', sa.DateTime(), nullable=True))
    op.drop_column('booking', 'booking_from')
    op.drop_column('booking', 'booking_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_to', mysql.DATETIME(), nullable=True))
    op.add_column('booking', sa.Column('booking_from', mysql.DATETIME(), nullable=True))
    op.drop_column('booking', 'booking_at')
    # ### end Alembic commands ###
