"""empty message

Revision ID: f7c00a0c23df
Revises: 52c1d9e13db4
Create Date: 2020-09-05 16:45:55.479938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c00a0c23df'
down_revision = '52c1d9e13db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_client', sa.Column('business_id', sa.String(length=255), nullable=True))
    op.add_column('business_client', sa.Column('license_number', sa.String(length=255), nullable=True))
    op.add_column('business_client', sa.Column('manager_name', sa.String(length=255), nullable=True))
    op.add_column('business_client', sa.Column('mobile_number_manager', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_client', 'mobile_number_manager')
    op.drop_column('business_client', 'manager_name')
    op.drop_column('business_client', 'license_number')
    op.drop_column('business_client', 'business_id')
    # ### end Alembic commands ###
